### ISSUE TITLE
Documentation is incorrect

### ISSUE THREAD

**Issue by arcturus** [cozy/cozy-vcard#13]
In the current readme we find the following code example:

```
var vcf = fs.readFileSync('test/friend.vcf', 'utf8');
var vparser = new VCardParser(vcf);
var vcontact = parser.components[0];
var vsomeprop = contact.properties[0]:
```

variables vparser and vcontact are then tried to be used as parser and contact.

**Comment by parro-it** [comment]
Also, I have to use 'parser.contacts[0];' instead of 'parser.components[0];'

**Comment by frankrousseau** [comment]
@arcturus Thank you for reporting. But I don't understand well what you mean. 

@parro-it Thank you to I made the fix you mention.

**Comment by parro-it** [comment]
yw. What artur means is that the example code should have been:

 ```javascript
var vcf = fs.readFileSync('test/friend.vcf', 'utf8');
var vparser = new VCardParser(vcf);
var vcontact = vparser.contacts[0];
var vsomeprop = vcontact.datapoints[0];
// vcontact.org == 'SuperCorp'
// vsomeprop.value == '+33123456789'
// vsomeprop.name == 'tel'
// vsomeprop.type == 'home'
// vsomeprop.pref == true
```

**Comment by frankrousseau** [comment]
Hello @parro-it. Sorry for the late answer. Is this issue solved?

**Comment by parro-it** [comment]
there was still some undefined vars, I've posted a PR that should solve.

**Comment by frankrousseau** [comment]
Ok let's close this issue then!

**Comment by frankrousseau** [comment]
Btw, thank you again for the fix!

**Comment by parro-it** [comment]
You're welcome!
