### ISSUE TITLE
Problem in Exporting vCard

### ISSUE THREAD

**Issue by nehakadam** [cozy/cozy-vcard#21]
Hi,

I was trying to export vCard, but it is returning "BEGIN:VCARD\nVERSION:3.0\nEND:VCARD\n" everytime. I used the same code written in Usage section. 

Can you please check my [code](https://tonicdev.com/nehakadam/cozy-vcard-export) and tell whether I am missing something in implementation.

**Comment by clochix** [comment]
Hi @nehakadam,

you should call `toVCF` on the contact itself, not on the array of contacts:
```javascript
    svCard = oLibCozyvCard.toVCF(ovCardElement);
    // instead of
    svCard = oLibCozyvCard.toVCF(ovCard);
```

Hope this helps ☺

**Comment by nehakadam** [comment]
Hey thanks it solved the issue.
