### ISSUE TITLE
Unsupported IM tags

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-vcard#9]
Issue reported by @hansbkk

Wow this is a big one! Every one of the IM handles from Google's export gets just silently dropped!

X-AIM:AIM
X-GTALK:gTalk
X-ICQ:ICQ
X-JABBER:Jabber
X-MSN:MSN
X-QQ:QQ
X-SKYPE:Skype
X-YAHOO:Yahoo

Workaround would be to enter these in notes only.

Cozy exports them (Twitter & Skype only) as:

X-;TYPE=TWITTER:@AAAFirst
X-;TYPE=SKYPE:AAFirstAAALast

and in fact Cozy uses the 'blank' "X-" label for company, all relationships, custom dates

rather than the more useful labels allowing grouping:
item10.X-ABDATE:2019-12-31
item10.X-ABLabel:Arbitrary Date

and

item12.X-ABRELATEDNAMES:Big Brother
item12.X-ABLabel:$!!$

**Comment by hansbkk** [comment]
Thanks Frank

FFR More general issue here: https://github.com/cozy/cozy-sync/issues/26

**Comment by aenario** [comment]
Note about this @jacquarg 
We need to figure out the more client-compatible way to export IM handles : I am affraid most client will silently drop the X-SKYPE and co.

The X-;TYPE=TWITTER:@AAAFirst is a bug. 
For datapoint with name="other", we should put directly the type after the X- and handle specially the types we "know" (aka all of the OP)

**Comment by hansbkk** [comment]
Test this - take google's export, transform to your choice of structure, then see if Google will re-import it correctly. If so, done & profit!

**Comment by frankrousseau** [comment]
It should be fixed by latest changes. Let's @hansbkk review the fixes :)
